### ISSUE TITLE
Link do videos on Stage 2 isn't working

### ISSUE THREAD

**Issue by luisofribeiro** [udacity/ipnd-webcasts#3]
Links to videos on the notes form stage 2 is redirecting to a error 404

i.e: https://plus.google.com/events/cvd7n15lqrmf267jfb4b978bo7c?authkey=CNiLyr-Q-t_I2AE

**Comment by SudKul** [comment]
Closing out the issue, as [Google+](https://support.google.com/googlecurrents/answer/9217723?hl=en#:~:text=On%20April%202%2C%202a019%20we,started%20before%20March%2031%2C%202019.&text=You%20can%20delete%20your%20Google%2B%20account%20before%20the%20consumer%20Google%2B%20shutdown.) has been shut down.
