### ISSUE TITLE
video in ipnd-webcasts/Stage_2/2015-03-24-python_debugging/ failed

### ISSUE THREAD

**Issue by dbhere** [udacity/ipnd-webcasts#4]
I cannot view the video in ipnd-webcasts/Stage_2/2015-03-24-python_debugging/
because it needs an extra authorization in G+.
only this video have the problem
[video](https://plus.google.com/u/0/events/centl78lqajmhq2erne9isecr74)

**Comment by SudKul** [comment]
Closing out the issue, as [Google+](https://support.google.com/googlecurrents/answer/9217723?hl=en#:~:text=On%20April%202%2C%202019%20we,started%20before%20March%2031%2C%202019.&text=You%20can%20delete%20your%20Google%2B%20account%20before%20the%20consumer%20Google%2B%20shutdown.) has been shut down.
